[build]
  publish = "dist"         
  command = "npm run build" 

[context.production]
  command = "npx prisma generate && npm run build"

[[redirects]]
  from = "/trpc/*"
  to = "/.netlify/functions/trpc/:splat"
  status = 200
  force = true
  headers = { Authorization = "{Authorization}" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200