[build]
  publish = "dist"
  command = "npx prisma generate && npm run build"

[context.production]
  command = "npx prisma generate && npm run build"

[[redirects]]
  from = "/trpc/*"
  to = "/.netlify/functions/trpc/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"