/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as UpdatePasswordRouteImport } from './../routes/update-password'
import { Route as ResetPasswordRouteImport } from './../routes/reset-password'
import { Route as RegisterRouteImport } from './../routes/register'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as EmailChangeRouteImport } from './../routes/email-change'
import { Route as AuthenticatedRouteRouteImport } from './../routes/_authenticated/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AuthenticatedProfileRouteImport } from './../routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './../routes/_authenticated/home'
import { Route as AuthenticatedStacksIndexRouteImport } from './../routes/_authenticated/stacks/index'
import { Route as AuthenticatedStacksNewRouteImport } from './../routes/_authenticated/stacks/new'
import { Route as AuthenticatedStacksStackIdDeleteRouteImport } from './../routes/_authenticated/stacks/$stackId/delete'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailChangeRoute = EmailChangeRouteImport.update({
  id: '/email-change',
  path: '/email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStacksIndexRoute =
  AuthenticatedStacksIndexRouteImport.update({
    id: '/stacks/',
    path: '/stacks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStacksNewRoute = AuthenticatedStacksNewRouteImport.update({
  id: '/stacks/new',
  path: '/stacks/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStacksStackIdDeleteRoute =
  AuthenticatedStacksStackIdDeleteRouteImport.update({
    id: '/stacks/$stackId/delete',
    path: '/stacks/$stackId/delete',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-change': typeof EmailChangeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/stacks/new': typeof AuthenticatedStacksNewRoute
  '/stacks/': typeof AuthenticatedStacksIndexRoute
  '/stacks/$stackId/delete': typeof AuthenticatedStacksStackIdDeleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-change': typeof EmailChangeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/stacks/new': typeof AuthenticatedStacksNewRoute
  '/stacks': typeof AuthenticatedStacksIndexRoute
  '/stacks/$stackId/delete': typeof AuthenticatedStacksStackIdDeleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/email-change': typeof EmailChangeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/stacks/new': typeof AuthenticatedStacksNewRoute
  '/_authenticated/stacks/': typeof AuthenticatedStacksIndexRoute
  '/_authenticated/stacks/$stackId/delete': typeof AuthenticatedStacksStackIdDeleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-change'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/update-password'
    | '/home'
    | '/profile'
    | '/stacks/new'
    | '/stacks/'
    | '/stacks/$stackId/delete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-change'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/update-password'
    | '/home'
    | '/profile'
    | '/stacks/new'
    | '/stacks'
    | '/stacks/$stackId/delete'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/email-change'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/update-password'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/stacks/new'
    | '/_authenticated/stacks/'
    | '/_authenticated/stacks/$stackId/delete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EmailChangeRoute: typeof EmailChangeRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-change': {
      id: '/email-change'
      path: '/email-change'
      fullPath: '/email-change'
      preLoaderRoute: typeof EmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stacks/': {
      id: '/_authenticated/stacks/'
      path: '/stacks'
      fullPath: '/stacks/'
      preLoaderRoute: typeof AuthenticatedStacksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stacks/new': {
      id: '/_authenticated/stacks/new'
      path: '/stacks/new'
      fullPath: '/stacks/new'
      preLoaderRoute: typeof AuthenticatedStacksNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stacks/$stackId/delete': {
      id: '/_authenticated/stacks/$stackId/delete'
      path: '/stacks/$stackId/delete'
      fullPath: '/stacks/$stackId/delete'
      preLoaderRoute: typeof AuthenticatedStacksStackIdDeleteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStacksNewRoute: typeof AuthenticatedStacksNewRoute
  AuthenticatedStacksIndexRoute: typeof AuthenticatedStacksIndexRoute
  AuthenticatedStacksStackIdDeleteRoute: typeof AuthenticatedStacksStackIdDeleteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStacksNewRoute: AuthenticatedStacksNewRoute,
  AuthenticatedStacksIndexRoute: AuthenticatedStacksIndexRoute,
  AuthenticatedStacksStackIdDeleteRoute: AuthenticatedStacksStackIdDeleteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EmailChangeRoute: EmailChangeRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
