/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as UpdatePasswordRouteImport } from './../routes/update-password'
import { Route as ResetPasswordRouteImport } from './../routes/reset-password'
import { Route as RegisterRouteImport } from './../routes/register'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as EmailChangeRouteImport } from './../routes/email-change'
import { Route as AuthenticatedRouteRouteImport } from './../routes/_authenticated/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AuthenticatedProfileRouteImport } from './../routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './../routes/_authenticated/home'
import { Route as AuthenticatedStacksIndexRouteImport } from './../routes/_authenticated/stacks/index'
import { Route as AuthenticatedStacksNewRouteImport } from './../routes/_authenticated/stacks/new'
import { Route as AuthenticatedStacksStackIdRouteRouteImport } from './../routes/_authenticated/stacks/$stackId/route'
import { Route as AuthenticatedStacksStackIdIndexRouteImport } from './../routes/_authenticated/stacks/$stackId/index'
import { Route as AuthenticatedStacksStackIdDeleteRouteImport } from './../routes/_authenticated/stacks/$stackId/delete'
import { Route as AuthenticatedStacksStackIdAddTrackIndexRouteImport } from './../routes/_authenticated/stacks/$stackId/add-track/index'
import { Route as AuthenticatedStacksStackIdSamplerTrackIdIndexRouteImport } from './../routes/_authenticated/stacks/$stackId/sampler/$trackId/index'
import { Route as AuthenticatedStacksStackIdPianoRollTrackIdIndexRouteImport } from './../routes/_authenticated/stacks/$stackId/piano-roll/$trackId/index'
import { Route as AuthenticatedStacksStackIdLibraryTrackIdIndexRouteImport } from './../routes/_authenticated/stacks/$stackId/library/$trackId/index'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailChangeRoute = EmailChangeRouteImport.update({
  id: '/email-change',
  path: '/email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStacksIndexRoute =
  AuthenticatedStacksIndexRouteImport.update({
    id: '/stacks/',
    path: '/stacks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStacksNewRoute = AuthenticatedStacksNewRouteImport.update({
  id: '/stacks/new',
  path: '/stacks/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStacksStackIdRouteRoute =
  AuthenticatedStacksStackIdRouteRouteImport.update({
    id: '/stacks/$stackId',
    path: '/stacks/$stackId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStacksStackIdIndexRoute =
  AuthenticatedStacksStackIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStacksStackIdRouteRoute,
  } as any)
const AuthenticatedStacksStackIdDeleteRoute =
  AuthenticatedStacksStackIdDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => AuthenticatedStacksStackIdRouteRoute,
  } as any)
const AuthenticatedStacksStackIdAddTrackIndexRoute =
  AuthenticatedStacksStackIdAddTrackIndexRouteImport.update({
    id: '/add-track/',
    path: '/add-track/',
    getParentRoute: () => AuthenticatedStacksStackIdRouteRoute,
  } as any)
const AuthenticatedStacksStackIdSamplerTrackIdIndexRoute =
  AuthenticatedStacksStackIdSamplerTrackIdIndexRouteImport.update({
    id: '/sampler/$trackId/',
    path: '/sampler/$trackId/',
    getParentRoute: () => AuthenticatedStacksStackIdRouteRoute,
  } as any)
const AuthenticatedStacksStackIdPianoRollTrackIdIndexRoute =
  AuthenticatedStacksStackIdPianoRollTrackIdIndexRouteImport.update({
    id: '/piano-roll/$trackId/',
    path: '/piano-roll/$trackId/',
    getParentRoute: () => AuthenticatedStacksStackIdRouteRoute,
  } as any)
const AuthenticatedStacksStackIdLibraryTrackIdIndexRoute =
  AuthenticatedStacksStackIdLibraryTrackIdIndexRouteImport.update({
    id: '/library/$trackId/',
    path: '/library/$trackId/',
    getParentRoute: () => AuthenticatedStacksStackIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-change': typeof EmailChangeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/stacks/$stackId': typeof AuthenticatedStacksStackIdRouteRouteWithChildren
  '/stacks/new': typeof AuthenticatedStacksNewRoute
  '/stacks/': typeof AuthenticatedStacksIndexRoute
  '/stacks/$stackId/delete': typeof AuthenticatedStacksStackIdDeleteRoute
  '/stacks/$stackId/': typeof AuthenticatedStacksStackIdIndexRoute
  '/stacks/$stackId/add-track/': typeof AuthenticatedStacksStackIdAddTrackIndexRoute
  '/stacks/$stackId/library/$trackId/': typeof AuthenticatedStacksStackIdLibraryTrackIdIndexRoute
  '/stacks/$stackId/piano-roll/$trackId/': typeof AuthenticatedStacksStackIdPianoRollTrackIdIndexRoute
  '/stacks/$stackId/sampler/$trackId/': typeof AuthenticatedStacksStackIdSamplerTrackIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-change': typeof EmailChangeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/stacks/new': typeof AuthenticatedStacksNewRoute
  '/stacks': typeof AuthenticatedStacksIndexRoute
  '/stacks/$stackId/delete': typeof AuthenticatedStacksStackIdDeleteRoute
  '/stacks/$stackId': typeof AuthenticatedStacksStackIdIndexRoute
  '/stacks/$stackId/add-track': typeof AuthenticatedStacksStackIdAddTrackIndexRoute
  '/stacks/$stackId/library/$trackId': typeof AuthenticatedStacksStackIdLibraryTrackIdIndexRoute
  '/stacks/$stackId/piano-roll/$trackId': typeof AuthenticatedStacksStackIdPianoRollTrackIdIndexRoute
  '/stacks/$stackId/sampler/$trackId': typeof AuthenticatedStacksStackIdSamplerTrackIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/email-change': typeof EmailChangeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/stacks/$stackId': typeof AuthenticatedStacksStackIdRouteRouteWithChildren
  '/_authenticated/stacks/new': typeof AuthenticatedStacksNewRoute
  '/_authenticated/stacks/': typeof AuthenticatedStacksIndexRoute
  '/_authenticated/stacks/$stackId/delete': typeof AuthenticatedStacksStackIdDeleteRoute
  '/_authenticated/stacks/$stackId/': typeof AuthenticatedStacksStackIdIndexRoute
  '/_authenticated/stacks/$stackId/add-track/': typeof AuthenticatedStacksStackIdAddTrackIndexRoute
  '/_authenticated/stacks/$stackId/library/$trackId/': typeof AuthenticatedStacksStackIdLibraryTrackIdIndexRoute
  '/_authenticated/stacks/$stackId/piano-roll/$trackId/': typeof AuthenticatedStacksStackIdPianoRollTrackIdIndexRoute
  '/_authenticated/stacks/$stackId/sampler/$trackId/': typeof AuthenticatedStacksStackIdSamplerTrackIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-change'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/update-password'
    | '/home'
    | '/profile'
    | '/stacks/$stackId'
    | '/stacks/new'
    | '/stacks/'
    | '/stacks/$stackId/delete'
    | '/stacks/$stackId/'
    | '/stacks/$stackId/add-track/'
    | '/stacks/$stackId/library/$trackId/'
    | '/stacks/$stackId/piano-roll/$trackId/'
    | '/stacks/$stackId/sampler/$trackId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-change'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/update-password'
    | '/home'
    | '/profile'
    | '/stacks/new'
    | '/stacks'
    | '/stacks/$stackId/delete'
    | '/stacks/$stackId'
    | '/stacks/$stackId/add-track'
    | '/stacks/$stackId/library/$trackId'
    | '/stacks/$stackId/piano-roll/$trackId'
    | '/stacks/$stackId/sampler/$trackId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/email-change'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/update-password'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/stacks/$stackId'
    | '/_authenticated/stacks/new'
    | '/_authenticated/stacks/'
    | '/_authenticated/stacks/$stackId/delete'
    | '/_authenticated/stacks/$stackId/'
    | '/_authenticated/stacks/$stackId/add-track/'
    | '/_authenticated/stacks/$stackId/library/$trackId/'
    | '/_authenticated/stacks/$stackId/piano-roll/$trackId/'
    | '/_authenticated/stacks/$stackId/sampler/$trackId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EmailChangeRoute: typeof EmailChangeRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-change': {
      id: '/email-change'
      path: '/email-change'
      fullPath: '/email-change'
      preLoaderRoute: typeof EmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stacks/': {
      id: '/_authenticated/stacks/'
      path: '/stacks'
      fullPath: '/stacks/'
      preLoaderRoute: typeof AuthenticatedStacksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stacks/new': {
      id: '/_authenticated/stacks/new'
      path: '/stacks/new'
      fullPath: '/stacks/new'
      preLoaderRoute: typeof AuthenticatedStacksNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stacks/$stackId': {
      id: '/_authenticated/stacks/$stackId'
      path: '/stacks/$stackId'
      fullPath: '/stacks/$stackId'
      preLoaderRoute: typeof AuthenticatedStacksStackIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stacks/$stackId/': {
      id: '/_authenticated/stacks/$stackId/'
      path: '/'
      fullPath: '/stacks/$stackId/'
      preLoaderRoute: typeof AuthenticatedStacksStackIdIndexRouteImport
      parentRoute: typeof AuthenticatedStacksStackIdRouteRoute
    }
    '/_authenticated/stacks/$stackId/delete': {
      id: '/_authenticated/stacks/$stackId/delete'
      path: '/delete'
      fullPath: '/stacks/$stackId/delete'
      preLoaderRoute: typeof AuthenticatedStacksStackIdDeleteRouteImport
      parentRoute: typeof AuthenticatedStacksStackIdRouteRoute
    }
    '/_authenticated/stacks/$stackId/add-track/': {
      id: '/_authenticated/stacks/$stackId/add-track/'
      path: '/add-track'
      fullPath: '/stacks/$stackId/add-track/'
      preLoaderRoute: typeof AuthenticatedStacksStackIdAddTrackIndexRouteImport
      parentRoute: typeof AuthenticatedStacksStackIdRouteRoute
    }
    '/_authenticated/stacks/$stackId/sampler/$trackId/': {
      id: '/_authenticated/stacks/$stackId/sampler/$trackId/'
      path: '/sampler/$trackId'
      fullPath: '/stacks/$stackId/sampler/$trackId/'
      preLoaderRoute: typeof AuthenticatedStacksStackIdSamplerTrackIdIndexRouteImport
      parentRoute: typeof AuthenticatedStacksStackIdRouteRoute
    }
    '/_authenticated/stacks/$stackId/piano-roll/$trackId/': {
      id: '/_authenticated/stacks/$stackId/piano-roll/$trackId/'
      path: '/piano-roll/$trackId'
      fullPath: '/stacks/$stackId/piano-roll/$trackId/'
      preLoaderRoute: typeof AuthenticatedStacksStackIdPianoRollTrackIdIndexRouteImport
      parentRoute: typeof AuthenticatedStacksStackIdRouteRoute
    }
    '/_authenticated/stacks/$stackId/library/$trackId/': {
      id: '/_authenticated/stacks/$stackId/library/$trackId/'
      path: '/library/$trackId'
      fullPath: '/stacks/$stackId/library/$trackId/'
      preLoaderRoute: typeof AuthenticatedStacksStackIdLibraryTrackIdIndexRouteImport
      parentRoute: typeof AuthenticatedStacksStackIdRouteRoute
    }
  }
}

interface AuthenticatedStacksStackIdRouteRouteChildren {
  AuthenticatedStacksStackIdDeleteRoute: typeof AuthenticatedStacksStackIdDeleteRoute
  AuthenticatedStacksStackIdIndexRoute: typeof AuthenticatedStacksStackIdIndexRoute
  AuthenticatedStacksStackIdAddTrackIndexRoute: typeof AuthenticatedStacksStackIdAddTrackIndexRoute
  AuthenticatedStacksStackIdLibraryTrackIdIndexRoute: typeof AuthenticatedStacksStackIdLibraryTrackIdIndexRoute
  AuthenticatedStacksStackIdPianoRollTrackIdIndexRoute: typeof AuthenticatedStacksStackIdPianoRollTrackIdIndexRoute
  AuthenticatedStacksStackIdSamplerTrackIdIndexRoute: typeof AuthenticatedStacksStackIdSamplerTrackIdIndexRoute
}

const AuthenticatedStacksStackIdRouteRouteChildren: AuthenticatedStacksStackIdRouteRouteChildren =
  {
    AuthenticatedStacksStackIdDeleteRoute:
      AuthenticatedStacksStackIdDeleteRoute,
    AuthenticatedStacksStackIdIndexRoute: AuthenticatedStacksStackIdIndexRoute,
    AuthenticatedStacksStackIdAddTrackIndexRoute:
      AuthenticatedStacksStackIdAddTrackIndexRoute,
    AuthenticatedStacksStackIdLibraryTrackIdIndexRoute:
      AuthenticatedStacksStackIdLibraryTrackIdIndexRoute,
    AuthenticatedStacksStackIdPianoRollTrackIdIndexRoute:
      AuthenticatedStacksStackIdPianoRollTrackIdIndexRoute,
    AuthenticatedStacksStackIdSamplerTrackIdIndexRoute:
      AuthenticatedStacksStackIdSamplerTrackIdIndexRoute,
  }

const AuthenticatedStacksStackIdRouteRouteWithChildren =
  AuthenticatedStacksStackIdRouteRoute._addFileChildren(
    AuthenticatedStacksStackIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStacksStackIdRouteRoute: typeof AuthenticatedStacksStackIdRouteRouteWithChildren
  AuthenticatedStacksNewRoute: typeof AuthenticatedStacksNewRoute
  AuthenticatedStacksIndexRoute: typeof AuthenticatedStacksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStacksStackIdRouteRoute:
    AuthenticatedStacksStackIdRouteRouteWithChildren,
  AuthenticatedStacksNewRoute: AuthenticatedStacksNewRoute,
  AuthenticatedStacksIndexRoute: AuthenticatedStacksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EmailChangeRoute: EmailChangeRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
